name: Build Dunder Mifflin application

run-name: Build Dunder Mifflin application

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PUBLISH_DIR: ${{ github.workspace }}/publish

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build --no-restore --configuration Release

      - name: Publish API
        working-directory: src/DunderMifflin.Api
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          dotnet publish ./DunderMifflin.Api.csproj \
            --configuration Release \
            --output ${{ env.PUBLISH_DIR }}/api
          # Zip what App Service expects (folder content)
          cd ${{ env.PUBLISH_DIR }}/api && zip -r dundermifflin.api.zip . && cd -

      - name: Publish remote MCP server
        working-directory: src/DunderMifflin.Mcp.Remote
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          dotnet publish ./DunderMifflin.Mcp.Remote.csproj \
            --configuration Release \
            --output ${{ env.PUBLISH_DIR }}/mcp
          # Zip what App Service expects (folder content)
          cd ${{ env.PUBLISH_DIR }}/mcp && zip -r dundermifflin.mcp.zip . && cd -

      - name: Upload API artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: dundermifflin-api-artifact
          path: ${{ env.PUBLISH_DIR }}/api/dundermifflin.api.zip

      - name: Upload remote MCP server artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: dundermifflin-mcp-artifact
          path: ${{ env.PUBLISH_DIR }}/mcp/dundermifflin.mcp.zip
